services:
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "55432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tg-watchdog
    restart: always
    env_file:
      - .env
    environment:
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL}
      - BOT_TOKEN=${BOT_TOKEN}
      - TARGET_CHAT_ID=${TARGET_CHAT_ID}
      - TIMEZONE=${TIMEZONE}
      - ACCOUNT1_API_ID=${ACCOUNT1_API_ID}
      - ACCOUNT1_API_HASH=${ACCOUNT1_API_HASH}
      - ACCOUNT1_USERNAME=${ACCOUNT1_USERNAME}
      - ACCOUNT1_USER_ID=${ACCOUNT1_USER_ID}
      - ACCOUNT2_API_ID=${ACCOUNT2_API_ID}
      - ACCOUNT2_API_HASH=${ACCOUNT2_API_HASH}
      - ACCOUNT2_USERNAME=${ACCOUNT2_USERNAME}
      - ACCOUNT2_USER_ID=${ACCOUNT2_USER_ID}
      - ACCOUNT3_API_ID=${ACCOUNT3_API_ID}
      - ACCOUNT3_API_HASH=${ACCOUNT3_API_HASH}
      - ACCOUNT3_USERNAME=${ACCOUNT3_USERNAME}
      - ACCOUNT3_USER_ID=${ACCOUNT3_USER_ID}
    depends_on:
      - redis
      - postgres
    ports:
      - "8010:8010"
    volumes:
      - ./sessions:/app/sessions
      - ./data/logs:/app/logs

volumes:
  redis_data:
  postgres_data:

