services:
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "55432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data


  app_dark:
    build: ./dark_ui
    volumes:
      - ./dark_ui:/app
    ports:
      - "8012:8010"
    env_file:
      - .env.docker
    depends_on:
      - redis
      - postgres

volumes:
  redis_data:
  postgres_data:

